#!/bin/bash

# Python Paar Compiler
# @version: 1.0
# @author: García García Alan Mauricio
# @author: Hernández Mora Alejandro

if [ ! -f src/pylex ];
then
	echo "pythonpc: fatal error: compiler files not found"
	exit
fi

if [ -z "$1" ];
then
	echo "pythonpc: fatal error: no input files"
	exit
fi

XPATH="`dirname \"$0\"`"
XPATH="`( cd \"$MY_PATH\" && pwd )`"
FILE=$1
./src/pylex $FILE &&
echo $FILE &&
cp -rv src/prueba.j lib/oolong/ &&
cd lib/oolong/ &&
java Oolong prueba.j &&
cp prueba.class "$XPATH"

#if [ ! -f src/output.j ];
#then
	#java lib/Oolong.class src/oolong.j
#fi
